import { useState } from 'react';
import { GripVertical } from 'lucide-react';
import type { MediationRecord } from '@/types';

export function ArrangeModal({ records, onClose, onSave }: { records: MediationRecord[]; onClose: () => void; onSave: (records: MediationRecord[]) => void }) {
  const [arrangedRecords, setArrangedRecords] = useState(records);
  const [draggedId, setDraggedId] = useState<string | null>(null);
  const handleDrop = (targetId: string) => { if (!draggedId || draggedId === targetId) return; setArrangedRecords((current) => { const fromIndex = current.findIndex((record) => record.id === draggedId); const toIndex = current.findIndex((record) => record.id === targetId); if (fromIndex < 0 || toIndex < 0) return current; const next = [...current]; const [moved] = next.splice(fromIndex, 1); next.splice(toIndex, 0, moved); return next; }); setDraggedId(null); };
  return <div className="no-print fixed inset-0 z-50 flex items-center justify-center bg-ink-900/60 p-4" role="presentation" onClick={onClose}><div className="flex max-h-[min(720px,calc(100vh-2rem))] w-full max-w-xl flex-col rounded-xl bg-white shadow-card-lg" role="dialog" aria-modal="true" aria-labelledby="arrange-records-title" onClick={(event) => event.stopPropagation()}><div className="border-b border-ink-100 px-5 py-4 sm:px-6"><h2 id="arrange-records-title" className="text-lg font-semibold text-ink-900">Arrange Records</h2><p className="mt-1 text-sm text-ink-500">Drag and drop records to set their order.</p></div><div className="min-h-0 flex-1 space-y-2 overflow-y-auto p-5 sm:p-6">{arrangedRecords.map((record) => <div key={record.id} draggable onDragStart={() => setDraggedId(record.id)} onDragEnd={() => setDraggedId(null)} onDragOver={(event) => event.preventDefault()} onDrop={() => handleDrop(record.id)} className={`flex cursor-grab items-center gap-3 rounded-lg border px-3 py-3 text-sm transition active:cursor-grabbing ${draggedId === record.id ? 'border-gold-400 bg-gold-50 opacity-60' : 'border-ink-200 bg-ink-50/40 hover:border-ink-300 hover:bg-white'}`}><GripVertical className="h-5 w-5 shrink-0 text-ink-400" aria-hidden="true" /><span className="min-w-0 truncate font-medium text-ink-800">{record.mediationCasePart}/{record.mediationCaseYear}</span><span className="truncate text-ink-500">{record.firstParty} vs. {record.secondParty}</span></div>)}</div><div className="flex justify-end gap-3 border-t border-ink-100 px-5 py-4 sm:px-6"><button type="button" className="btn-ghost" onClick={onClose}>Close</button><button type="button" className="btn-primary" onClick={() => onSave(arrangedRecords.map((record, index) => ({ ...record, sortOrder: index })))}>Save Order</button></div></div></div>;
}